### ISSUE TITLE
As a content creator I want to livestream directly from my webcam

### ISSUE THREAD

**Issue by pabloVoorvaart** [NFTsTv/nftstv#8]
Required for alpha: 

- [ ] Rework control buttons and status feedback

**Comment by Mario-SO** [comment]
maybe related to #24 ?

**Comment by Mario-SO** [comment]
The title of the issue is actually done, you can stream from your webcam but still with some problems to solve. I think we can close this one and create other issues that give more detail over the problems that exist when streaming with the webcam.
